services:
  - type: web
    name: persbudgapp-frontend
    env: static
    rootDir: persbudgapp-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeploy: true